export const authConstants = {
    LOGIN_REQUEST:'LOGIN REQUEST',
    LOGIN_FAILURE: 'LOGIN FAILURE',
    LOGIN_SUCCESS: 'LOGIN SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
}

export const userConstants = {
    USER_REGISTER_REQUEST : 'REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'REGISTER_FAILURE', 
}